apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Username: "guest"
  Payments__ApprovalRate: "0.8"
  Redis__ConnectionString: "redis:6379"
